<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Eylül Asuman">

<title>Credit Limit</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="CreditLimit_files/libs/clipboard/clipboard.min.js"></script>
<script src="CreditLimit_files/libs/quarto-html/quarto.js"></script>
<script src="CreditLimit_files/libs/quarto-html/popper.min.js"></script>
<script src="CreditLimit_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="CreditLimit_files/libs/quarto-html/anchor.min.js"></script>
<link href="CreditLimit_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="CreditLimit_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="CreditLimit_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="CreditLimit_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="CreditLimit_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Credit Limit</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Eylül Asuman </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="credit-limit-dataset" class="level1">
<h1>Credit Limit Dataset</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"CreditLimit.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">CLIENTNUM =</span> <span class="fu">as.character</span>(CLIENTNUM))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-fig.asp="0.614">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 14
  CLIENTNUM Attrition_Flag   Customer_Age Gender Dependent_count Education_Level
  &lt;chr&gt;     &lt;chr&gt;                   &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt; &lt;chr&gt;          
1 768805383 Existing Custom…           45 M                    3 High School    
2 818770008 Existing Custom…           49 F                    5 Graduate       
3 713982108 Existing Custom…           51 M                    3 Graduate       
4 769911858 Existing Custom…           40 F                    4 High School    
5 709106358 Existing Custom…           40 M                    3 Uneducated     
6 713061558 Existing Custom…           44 M                    2 Graduate       
# ℹ 8 more variables: Marital_Status &lt;chr&gt;, Income_Category &lt;chr&gt;,
#   Card_Category &lt;chr&gt;, Months_on_book &lt;dbl&gt;, Credit_Limit &lt;dbl&gt;,
#   Total_Trans_Amt &lt;dbl&gt;, Total_Ct_Chng_Q4_Q1 &lt;dbl&gt;,
#   Avg_Utilization_Ratio &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell" data-fig.asp="0.614">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">droplevels</span>(data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  CLIENTNUM         Attrition_Flag      Customer_Age     Gender         
 Length:7641        Length:7641        Min.   :26.0   Length:7641       
 Class :character   Class :character   1st Qu.:41.0   Class :character  
 Mode  :character   Mode  :character   Median :46.0   Mode  :character  
                                       Mean   :46.3                     
                                       3rd Qu.:52.0                     
                                       Max.   :73.0                     
 Dependent_count Education_Level    Marital_Status     Income_Category   
 Min.   :0.000   Length:7641        Length:7641        Length:7641       
 1st Qu.:1.000   Class :character   Class :character   Class :character  
 Median :2.000   Mode  :character   Mode  :character   Mode  :character  
 Mean   :2.352                                                           
 3rd Qu.:3.000                                                           
 Max.   :5.000                                                           
 Card_Category      Months_on_book   Credit_Limit   Total_Trans_Amt
 Length:7641        Min.   :13.00   Min.   : 1438   Min.   :  510  
 Class :character   1st Qu.:31.00   1st Qu.: 2507   1st Qu.: 2109  
 Mode  :character   Median :36.00   Median : 4343   Median : 3866  
                    Mean   :35.95   Mean   : 8559   Mean   : 4415  
                    3rd Qu.:40.00   3rd Qu.:10877   3rd Qu.: 4751  
                    Max.   :56.00   Max.   :34516   Max.   :17995  
 Total_Ct_Chng_Q4_Q1 Avg_Utilization_Ratio
 Min.   :0.0000      Min.   :0.0000       
 1st Qu.:0.5830      1st Qu.:0.0250       
 Median :0.7000      Median :0.1840       
 Mean   :0.7115      Mean   :0.2807       
 3rd Qu.:0.8180      3rd Qu.:0.5130       
 Max.   :3.7140      Max.   :0.9990       </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data<span class="sc">$</span>Credit_Limit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   1438    2507    4343    8559   10877   34516 </code></pre>
</div>
</div>
<section id="variables" class="level4">
<h4 class="anchored" data-anchor-id="variables">Variables</h4>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 75%">
</colgroup>
<tbody>
<tr class="odd">
<td>CLIENTNUM</td>
<td>Client number. Unique identifier for the customer holding the account.</td>
</tr>
<tr class="even">
<td>Attrition_Flag</td>
<td>Internal event (customer activity) variable - if the account is closed then 1 else 0</td>
</tr>
<tr class="odd">
<td>Customer_Age</td>
<td>Demographic variable - Customer’s Age in Years</td>
</tr>
<tr class="even">
<td>Gender</td>
<td>Demographic variable - M=Male, F=Female</td>
</tr>
<tr class="odd">
<td>Dependent_count</td>
<td>Demographic variable - Number of dependents</td>
</tr>
<tr class="even">
<td>Education_Level</td>
<td>Demographic variable - Educational Qualification of the account holder (example: high school, college graduate, etc.)</td>
</tr>
<tr class="odd">
<td>Marital_Status</td>
<td>Demographic variable - Married, Single, Divorced, Unknown</td>
</tr>
<tr class="even">
<td>Income_Category</td>
<td>Demographic variable - Annual Income Category of the account holder (&lt; $40K, $40K - 60K, $60K - $80K, $80K-$120K, &gt;</td>
</tr>
<tr class="odd">
<td>Card_Category</td>
<td>Product Variable - Type of Card (Blue, Silver, Gold, Platinum)</td>
</tr>
<tr class="even">
<td>Months_on_book</td>
<td>Period of relationship with bank</td>
</tr>
<tr class="odd">
<td>Credit_Limit</td>
<td>Credit Limit on the Credit Card</td>
</tr>
<tr class="even">
<td>Total_Trans_Amt</td>
<td>Total Transaction Amount (Last 12 months)</td>
</tr>
<tr class="odd">
<td>Total_Trans_Ct</td>
<td>Total Transaction Count (Last 12 months)</td>
</tr>
<tr class="even">
<td>Avg_Utilization_Ratio</td>
<td>Average Card Utilization Ratio</td>
</tr>
</tbody>
</table>
<div class="cell" data-fig.asp="1.2">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Attrition_Flag) <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="co">#filter(Credit_Limit&gt;10000) %&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>CLIENTNUM,<span class="at">y=</span>Credit_Limit))<span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color=</span>Attrition_Flag), <span class="at">alpha=</span><span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept=</span><span class="dv">10877</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"salmon2"</span>, <span class="at">linewidth=</span><span class="fl">1.</span>)<span class="sc">+</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept=</span><span class="dv">8559</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">linewidth=</span><span class="fl">1.1</span>)<span class="sc">+</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept=</span><span class="dv">4343</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"dodgerblue2"</span>, <span class="at">linewidth=</span><span class="fl">1.1</span>)<span class="sc">+</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept=</span> <span class="dv">2507</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"yellow"</span>, <span class="at">linewidth=</span><span class="fl">1.1</span>)<span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept=</span> <span class="dv">1438</span>, <span class="at">linetype=</span><span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"violetred"</span>, <span class="at">linewidth=</span><span class="fl">1.1</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>p1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CreditLimit_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(Credit_Limit <span class="sc">~</span> Attrition_Flag , <span class="at">data=</span>data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Attrition_Flag    min      Q1 median       Q3   max     mean       sd    n
1 Attrited Customer 1438.3 2056.50   4109  9954.00 34516 8222.205 9249.033 1211
2 Existing Customer 1438.3 2570.25   4421 10989.25 34516 8622.648 9145.102 6430
  missing
1       0
2       0</code></pre>
</div>
</div>
<div class="cell" data-fig.asp="0.614">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Credit_Limit))<span class="sc">+</span><span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">color=</span>Attrition_Flag))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CreditLimit_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Attrition_Flag) <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Credit_Limit, <span class="at">y =</span> Attrition_Flag)) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">color=</span><span class="st">"orange"</span>) <span class="sc">+</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CreditLimit_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(Credit_Limit <span class="sc">~</span> Months_on_book   , <span class="at">data=</span>data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Months_on_book    min      Q1 median       Q3   max      mean        sd    n
1              13 1438.3 2028.50 3290.0  5894.00 28174  5046.153  5146.893   43
2              14 2163.0 3232.50 4015.0  7252.00 14853  5757.182  3703.339   11
3              15 1438.3 2166.00 3682.0  4662.00 23399  5022.743  5117.804   21
4              16 1438.3 2546.00 3665.0 10705.00 34516  7595.600  8555.871   21
5              17 1438.3 2624.75 3336.5  6668.25 34516  6010.706  6634.134   32
6              18 1438.3 2082.50 2963.0  5689.50 34516  5759.812  7080.179   43
7              19 1438.3 2907.75 4161.0  8661.25 34516  7744.485  8510.888   48
8              20 1438.3 2235.00 4342.0 10486.00 34516  7972.861  8818.530   57
9              21 1438.3 2272.00 3433.0  6315.00 34516  6768.005  7905.755   65
10             22 1438.3 2049.75 3243.5  8669.75 34516  7828.247  9791.350   76
11             23 1438.3 2400.00 3955.0  7567.00 34516  6741.265  7223.764   93
12             24 1438.3 3263.50 4739.0 11314.25 34516  8527.339  8109.368  114
13             25 1438.3 2316.50 4364.0  9260.00 34516  7088.698  6776.503  130
14             26 1438.3 2375.25 3447.0  7305.50 34516  7318.260  8422.210  136
15             27 1438.3 2247.00 3901.0 11820.00 34516  8194.087  8719.341  163
16             28 1438.3 2495.00 4372.5 10253.50 34516  8121.264  8590.697  218
17             29 1438.3 2592.50 4394.0 11788.00 34516  8789.574  9377.311  179
18             30 1438.3 2579.00 4579.0 11463.00 34516  8532.811  8663.696  229
19             31 1438.3 2635.75 5017.5 12784.75 34516  9539.566  9936.856  244
20             32 1438.3 2624.00 4429.0 13162.00 34516  9898.546 10456.203  217
21             33 1438.3 2645.00 5651.0 13480.75 34516  9923.707 10121.727  238
22             34 1438.3 2545.00 5057.0 13561.50 34516  9090.720  8849.921  260
23             35 1438.3 2555.00 4505.0 11096.00 34516  8902.528  9605.196  253
24             36 1438.3 2464.00 4129.0 10350.00 34516  8451.874  9302.606 1833
25             37 1438.3 2589.00 4820.0 13119.00 34516  9557.691 10001.451  268
26             38 1438.3 2655.00 5481.0 12836.00 34516 10051.152 10200.089  261
27             39 1438.3 2751.75 5758.0 12740.75 34516  9506.061  9369.716  252
28             40 1438.3 2684.75 4545.0 11228.50 34516  8689.877  9144.020  258
29             41 1438.3 2596.00 4745.0 11669.00 34516  9122.250  9442.085  221
30             42 1438.3 2500.00 5168.0 13813.50 34516 10071.779 10577.280  199
31             43 1438.3 2239.25 3722.5  8389.50 34516  7435.673  8297.608  206
32             44 1438.3 2599.50 4153.0 11446.50 34516  8962.704  9799.856  179
33             45 1438.3 2312.00 4531.0 13287.00 34516  9243.281  9668.996  173
34             46 1438.3 2388.50 4629.0 10201.50 34516  8308.921  8748.402  151
35             47 1438.3 2497.25 4421.0  9407.00 34516  7412.955  7570.954  138
36             48 1438.3 2551.00 3776.5 10054.50 34516  8073.854  8913.868  118
37             49 1438.3 2414.00 3949.0  9788.00 34516  7858.370  9007.222  105
38             50 1438.3 2854.50 4974.5 12030.50 34516  8615.849  8216.227   76
39             51 1438.3 2130.50 5042.0  9497.00 34516  7787.571  8350.055   59
40             52 1438.3 2443.00 3088.0 10527.00 34516  8017.975  9053.521   44
41             53 1438.3 2503.50 3374.5  6283.50 34516  6960.425  8382.022   68
42             54 1438.3 2889.50 4890.5 10158.75 31680  7939.115  7426.462   40
43             55 1438.3 2419.00 3556.0  9922.50 34516  7287.722  8001.582   23
44             56 1438.3 2552.25 3544.0  6932.75 29100  5135.254  4196.346   78
   missing
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
30       0
31       0
32       0
33       0
34       0
35       0
36       0
37       0
38       0
39       0
40       0
41       0
42       0
43       0
44       0</code></pre>
</div>
</div>
<div class="cell" data-fig.asp="0.614">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Attrition_Flag) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Months_on_book, <span class="at">y =</span> Attrition_Flag)) <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">color=</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CreditLimit_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell" data-fig.asp="0.614">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Months_on_book))<span class="sc">+</span><span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">color=</span>Attrition_Flag))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CreditLimit_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(Credit_Limit <span class="sc">~</span> Education_Level , <span class="at">data=</span>data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Education_Level    min      Q1 median       Q3   max     mean       sd    n
1         College 1438.3 2492.00 4312.0 10797.00 34516 8702.469 9458.070  905
2       Doctorate 1438.3 2360.00 4142.0  9966.00 34516 8158.551 8889.491  381
3        Graduate 1438.3 2519.25 4390.0 10608.75 34516 8465.664 9087.757 2796
4     High School 1438.3 2561.00 4253.5 10475.00 34516 8437.665 9002.617 1788
5   Post-Graduate 1438.3 2566.00 4453.0 11236.00 34516 8690.469 9302.215  469
6      Uneducated 1438.3 2475.50 4448.5 11711.75 34516 8897.239 9361.034 1302
  missing
1       0
2       0
3       0
4       0
5       0
6       0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Credit_Limit))<span class="sc">+</span><span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">color=</span>Education_Level))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CreditLimit_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(Credit_Limit <span class="sc">~</span> Gender , <span class="at">data=</span>data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Gender    min   Q1 median       Q3   max      mean        sd    n missing
1      F 1438.3 2035 2831.5  4548.75 23981  3965.095  3185.273 3626       0
2      M 1438.3 3770 8851.0 19068.50 34516 12708.166 10692.579 4015       0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Credit_Limit))<span class="sc">+</span><span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">color=</span>Gender))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CreditLimit_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(Credit_Limit <span class="sc">~</span> Marital_Status , <span class="at">data=</span>data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Marital_Status    min      Q1 median       Q3   max     mean       sd    n
1       Divorced 1438.3 2543.00 4701.0 10991.00 34516 9035.851 9545.679  569
2        Married 1438.3 2494.75 4138.5  9824.25 34516 8006.741 8634.839 3564
3         Single 1438.3 2484.00 4508.0 11677.25 34516 8975.545 9581.458 2948
4        Unknown 1438.3 2650.25 4942.0 13141.25 34516 9398.906 9576.261  560
  missing
1       0
2       0
3       0
4       0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Credit_Limit))<span class="sc">+</span><span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">color=</span>Marital_Status))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CreditLimit_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(Credit_Limit <span class="sc">~</span> Income_Category , <span class="at">data=</span>data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Income_Category    min     Q1  median       Q3   max      mean        sd    n
1         $120K + 1438.3 8053.0 18214.0 34516.00 34516 19535.017 12111.664  607
2     $40K - $60K 1438.3 2441.0  3659.0  6629.00 23981  5384.891  4446.492 1521
3     $60K - $80K 1438.3 3603.5  7688.0 15360.50 34516 10772.924  8889.838 1192
4    $80K - $120K 1438.3 5700.5 13246.5 25615.25 34516 16072.945 11295.974 1316
5  Less than $40K 1438.3 2020.0  2781.0  4311.00 15987  3780.107  2782.746 3005
  missing
1       0
2       0
3       0
4       0
5       0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(Credit_Limit))<span class="sc">+</span><span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">color=</span>Income_Category))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CreditLimit_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="linear-regression" class="level4">
<h4 class="anchored" data-anchor-id="linear-regression">Linear Regression</h4>
<p><span class="math display">\[
\text{Credit_Limit} = \beta_0 + \beta_1 (\text{Parameters}) + \varepsilon
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>lmcreditlimit <span class="ot">&lt;-</span> <span class="fu">lm</span>(Credit_Limit <span class="sc">~</span> . <span class="sc">-</span>CLIENTNUM, data)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmcreditlimit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Credit_Limit ~ . - CLIENTNUM, data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-22144.9  -3357.2    159.6   2499.3  20707.3 

Coefficients:
                                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                      1.624e+04  6.560e+02  24.751  &lt; 2e-16 ***
Attrition_FlagExisting Customer  1.281e+03  1.903e+02   6.729 1.83e-11 ***
Customer_Age                     1.457e+01  1.326e+01   1.099 0.271747    
GenderM                          4.273e+02  2.334e+02   1.831 0.067144 .  
Dependent_count                  1.573e+02  5.084e+01   3.095 0.001978 ** 
Education_LevelDoctorate        -2.168e+02  3.444e+02  -0.630 0.528973    
Education_LevelGraduate          1.111e+02  2.155e+02   0.516 0.606039    
Education_LevelHigh School       1.674e+01  2.299e+02   0.073 0.941959    
Education_LevelPost-Graduate     3.247e+02  3.207e+02   1.012 0.311459    
Education_LevelUneducated        3.756e+02  2.439e+02   1.540 0.123591    
Marital_StatusMarried           -9.346e+02  2.550e+02  -3.665 0.000249 ***
Marital_StatusSingle            -3.433e+02  2.582e+02  -1.330 0.183642    
Marital_StatusUnknown           -3.892e+02  3.356e+02  -1.160 0.246271    
Income_Category$40K - $60K      -1.173e+04  3.047e+02 -38.488  &lt; 2e-16 ***
Income_Category$60K - $80K      -8.010e+03  2.821e+02 -28.394  &lt; 2e-16 ***
Income_Category$80K - $120K     -3.046e+03  2.770e+02 -10.995  &lt; 2e-16 ***
Income_CategoryLess than $40K   -1.247e+04  3.352e+02 -37.213  &lt; 2e-16 ***
Card_CategoryGold                1.627e+04  6.055e+02  26.871  &lt; 2e-16 ***
Card_CategoryPlatinum            1.626e+04  1.633e+03   9.958  &lt; 2e-16 ***
Card_CategorySilver              1.343e+04  2.875e+02  46.706  &lt; 2e-16 ***
Months_on_book                  -6.559e-01  1.321e+01  -0.050 0.960400    
Total_Trans_Amt                  1.415e-01  1.944e-02   7.282 3.61e-13 ***
Total_Ct_Chng_Q4_Q1              1.430e+02  2.829e+02   0.505 0.613264    
Avg_Utilization_Ratio           -7.888e+03  2.590e+02 -30.458  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5630 on 7617 degrees of freedom
Multiple R-squared:  0.6236,    Adjusted R-squared:  0.6224 
F-statistic: 548.6 on 23 and 7617 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell" data-fig.asp="0.614">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lmcreditlimit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CreditLimit_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Model explains %62.24 of all data.</p>
<p><code>Card_Category</code>, <code>Income_Category</code>, <code>Avg_Utilization_Ratio</code>, <code>Total_Trans_Amt</code> and being married and existing customer are highly related to determine credit card limit. <code>Dependent_count</code> and <code>Gender</code> provide also meaningful contribution.</p>
<div class="cell" data-fig.asp="0.914">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> data, <span class="fu">aes</span>(<span class="at">x =</span> Credit_Limit, <span class="at">y =</span> Total_Trans_Amt)) <span class="sc">+</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">col =</span> <span class="st">"dodgerblue3"</span>) <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="fu">theme</span>(<span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"white"</span>),</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="at">axis.line.x=</span><span class="fu">element_line</span>(),</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="at">axis.line.y=</span><span class="fu">element_line</span>()) <span class="sc">+</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggtitle</span>(<span class="st">"Linear Model Fitted to Data"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CreditLimit_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="better-model" class="level4">
<h4 class="anchored" data-anchor-id="better-model">Better Model?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>Best_Subset <span class="ot">&lt;-</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">regsubsets</span>(Credit_Limit <span class="sc">~</span> . <span class="sc">-</span>CLIENTNUM,</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span>data,</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">nbest =</span> <span class="dv">1</span>,      <span class="co"># 1 best model for each number of predictors</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">nvmax =</span> <span class="cn">NULL</span>,    <span class="co"># NULL for no limit on number of variables</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">force.in =</span> <span class="cn">NULL</span>, <span class="at">force.out =</span> <span class="cn">NULL</span>,</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">method =</span> <span class="st">"exhaustive"</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>summary_best_subset <span class="ot">&lt;-</span> <span class="fu">summary</span>(Best_Subset)</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="fu">as.data.frame</span>(summary_best_subset<span class="sc">$</span>outmat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Attrition_FlagExisting Customer Customer_Age GenderM Dependent_count
1  ( 1 )                                                                      
2  ( 1 )                                                     *                
3  ( 1 )                                                                      
4  ( 1 )                                                                      
5  ( 1 )                                                                      
6  ( 1 )                                                                      
7  ( 1 )                                                                      
8  ( 1 )                                                                      
9  ( 1 )                                                                      
10  ( 1 )                               *                                     
11  ( 1 )                               *                                     
12  ( 1 )                               *                                    *
13  ( 1 )                               *                                    *
14  ( 1 )                               *                    *               *
15  ( 1 )                               *            *       *               *
16  ( 1 )                               *            *       *               *
17  ( 1 )                               *            *       *               *
18  ( 1 )                               *            *       *               *
19  ( 1 )                               *            *       *               *
20  ( 1 )                               *            *       *               *
21  ( 1 )                               *            *       *               *
22  ( 1 )                               *            *       *               *
23  ( 1 )                               *            *       *               *
          Education_LevelDoctorate Education_LevelGraduate
1  ( 1 )                                                  
2  ( 1 )                                                  
3  ( 1 )                                                  
4  ( 1 )                                                  
5  ( 1 )                                                  
6  ( 1 )                                                  
7  ( 1 )                                                  
8  ( 1 )                                                  
9  ( 1 )                                                  
10  ( 1 )                                                 
11  ( 1 )                                                 
12  ( 1 )                                                 
13  ( 1 )                                                 
14  ( 1 )                                                 
15  ( 1 )                                                 
16  ( 1 )                                                 
17  ( 1 )                        *                        
18  ( 1 )                                                 
19  ( 1 )                        *                        
20  ( 1 )                        *                       *
21  ( 1 )                        *                       *
22  ( 1 )                        *                       *
23  ( 1 )                        *                       *
          Education_LevelHigh School Education_LevelPost-Graduate
1  ( 1 )                                                         
2  ( 1 )                                                         
3  ( 1 )                                                         
4  ( 1 )                                                         
5  ( 1 )                                                         
6  ( 1 )                                                         
7  ( 1 )                                                         
8  ( 1 )                                                         
9  ( 1 )                                                         
10  ( 1 )                                                        
11  ( 1 )                                                        
12  ( 1 )                                                        
13  ( 1 )                                                        
14  ( 1 )                                                        
15  ( 1 )                                                        
16  ( 1 )                                                       *
17  ( 1 )                                                       *
18  ( 1 )                                                       *
19  ( 1 )                                                       *
20  ( 1 )                                                       *
21  ( 1 )                                                       *
22  ( 1 )                          *                            *
23  ( 1 )                          *                            *
          Education_LevelUneducated Marital_StatusMarried Marital_StatusSingle
1  ( 1 )                                                                      
2  ( 1 )                                                                      
3  ( 1 )                                                                      
4  ( 1 )                                                                      
5  ( 1 )                                                                      
6  ( 1 )                                                                      
7  ( 1 )                                                                      
8  ( 1 )                                                                      
9  ( 1 )                                                                      
10  ( 1 )                                                                     
11  ( 1 )                                               *                     
12  ( 1 )                                               *                     
13  ( 1 )                         *                     *                     
14  ( 1 )                         *                     *                     
15  ( 1 )                         *                     *                     
16  ( 1 )                         *                     *                     
17  ( 1 )                         *                     *                     
18  ( 1 )                         *                     *                    *
19  ( 1 )                         *                     *                    *
20  ( 1 )                         *                     *                    *
21  ( 1 )                         *                     *                    *
22  ( 1 )                         *                     *                    *
23  ( 1 )                         *                     *                    *
          Marital_StatusUnknown Income_Category$40K - $60K
1  ( 1 )                                                  
2  ( 1 )                                                  
3  ( 1 )                                                 *
4  ( 1 )                                                 *
5  ( 1 )                                                 *
6  ( 1 )                                                 *
7  ( 1 )                                                 *
8  ( 1 )                                                 *
9  ( 1 )                                                 *
10  ( 1 )                                                *
11  ( 1 )                                                *
12  ( 1 )                                                *
13  ( 1 )                                                *
14  ( 1 )                                                *
15  ( 1 )                                                *
16  ( 1 )                                                *
17  ( 1 )                                                *
18  ( 1 )                     *                          *
19  ( 1 )                     *                          *
20  ( 1 )                     *                          *
21  ( 1 )                     *                          *
22  ( 1 )                     *                          *
23  ( 1 )                     *                          *
          Income_Category$60K - $80K Income_Category$80K - $120K
1  ( 1 )                                                        
2  ( 1 )                                                        
3  ( 1 )                                                        
4  ( 1 )                                                        
5  ( 1 )                           *                            
6  ( 1 )                           *                            
7  ( 1 )                           *                           *
8  ( 1 )                           *                           *
9  ( 1 )                           *                           *
10  ( 1 )                          *                           *
11  ( 1 )                          *                           *
12  ( 1 )                          *                           *
13  ( 1 )                          *                           *
14  ( 1 )                          *                           *
15  ( 1 )                          *                           *
16  ( 1 )                          *                           *
17  ( 1 )                          *                           *
18  ( 1 )                          *                           *
19  ( 1 )                          *                           *
20  ( 1 )                          *                           *
21  ( 1 )                          *                           *
22  ( 1 )                          *                           *
23  ( 1 )                          *                           *
          Income_CategoryLess than $40K Card_CategoryGold Card_CategoryPlatinum
1  ( 1 )                                                                       
2  ( 1 )                                                                       
3  ( 1 )                              *                                        
4  ( 1 )                              *                                        
5  ( 1 )                              *                                        
6  ( 1 )                              *                 *                      
7  ( 1 )                              *                 *                      
8  ( 1 )                              *                 *                     *
9  ( 1 )                              *                 *                     *
10  ( 1 )                             *                 *                     *
11  ( 1 )                             *                 *                     *
12  ( 1 )                             *                 *                     *
13  ( 1 )                             *                 *                     *
14  ( 1 )                             *                 *                     *
15  ( 1 )                             *                 *                     *
16  ( 1 )                             *                 *                     *
17  ( 1 )                             *                 *                     *
18  ( 1 )                             *                 *                     *
19  ( 1 )                             *                 *                     *
20  ( 1 )                             *                 *                     *
21  ( 1 )                             *                 *                     *
22  ( 1 )                             *                 *                     *
23  ( 1 )                             *                 *                     *
          Card_CategorySilver Months_on_book Total_Trans_Amt
1  ( 1 )                                                    
2  ( 1 )                    *                               
3  ( 1 )                    *                               
4  ( 1 )                    *                               
5  ( 1 )                    *                               
6  ( 1 )                    *                               
7  ( 1 )                    *                               
8  ( 1 )                    *                               
9  ( 1 )                    *                              *
10  ( 1 )                   *                              *
11  ( 1 )                   *                              *
12  ( 1 )                   *                              *
13  ( 1 )                   *                              *
14  ( 1 )                   *                              *
15  ( 1 )                   *                              *
16  ( 1 )                   *                              *
17  ( 1 )                   *                              *
18  ( 1 )                   *                              *
19  ( 1 )                   *                              *
20  ( 1 )                   *                              *
21  ( 1 )                   *                              *
22  ( 1 )                   *                              *
23  ( 1 )                   *              *               *
          Total_Ct_Chng_Q4_Q1 Avg_Utilization_Ratio
1  ( 1 )                                          *
2  ( 1 )                                           
3  ( 1 )                                           
4  ( 1 )                                          *
5  ( 1 )                                          *
6  ( 1 )                                          *
7  ( 1 )                                          *
8  ( 1 )                                          *
9  ( 1 )                                          *
10  ( 1 )                                         *
11  ( 1 )                                         *
12  ( 1 )                                         *
13  ( 1 )                                         *
14  ( 1 )                                         *
15  ( 1 )                                         *
16  ( 1 )                                         *
17  ( 1 )                                         *
18  ( 1 )                                         *
19  ( 1 )                                         *
20  ( 1 )                                         *
21  ( 1 )                   *                     *
22  ( 1 )                   *                     *
23  ( 1 )                   *                     *</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which.max</span>(summary_best_subset<span class="sc">$</span>adjr2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>summary_best_subset<span class="sc">$</span>which[<span class="dv">16</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    (Intercept) Attrition_FlagExisting Customer 
                           TRUE                            TRUE 
                   Customer_Age                         GenderM 
                           TRUE                            TRUE 
                Dependent_count        Education_LevelDoctorate 
                           TRUE                           FALSE 
        Education_LevelGraduate      Education_LevelHigh School 
                          FALSE                           FALSE 
   Education_LevelPost-Graduate       Education_LevelUneducated 
                           TRUE                            TRUE 
          Marital_StatusMarried            Marital_StatusSingle 
                           TRUE                           FALSE 
          Marital_StatusUnknown      Income_Category$40K - $60K 
                          FALSE                            TRUE 
     Income_Category$60K - $80K     Income_Category$80K - $120K 
                           TRUE                            TRUE 
  Income_CategoryLess than $40K               Card_CategoryGold 
                           TRUE                            TRUE 
          Card_CategoryPlatinum             Card_CategorySilver 
                           TRUE                            TRUE 
                 Months_on_book                 Total_Trans_Amt 
                          FALSE                            TRUE 
            Total_Ct_Chng_Q4_Q1           Avg_Utilization_Ratio 
                          FALSE                            TRUE </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>lmcreditlimitbetter <span class="ot">&lt;-</span> <span class="fu">lm</span>(Credit_Limit <span class="sc">~</span> Attrition_Flag <span class="sc">+</span> Customer_Age <span class="sc">+</span> Gender <span class="sc">+</span> Dependent_count<span class="sc">+</span>  Marital_Status <span class="sc">+</span> Income_Category <span class="sc">+</span> Card_Category <span class="sc">+</span> Total_Trans_Amt <span class="sc">+</span> Avg_Utilization_Ratio, data)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmcreditlimitbetter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Credit_Limit ~ Attrition_Flag + Customer_Age + Gender + 
    Dependent_count + Marital_Status + Income_Category + Card_Category + 
    Total_Trans_Amt + Avg_Utilization_Ratio, data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-21870.4  -3361.1    158.3   2489.1  20636.8 

Coefficients:
                                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                      1.644e+04  6.141e+02  26.774  &lt; 2e-16 ***
Attrition_FlagExisting Customer  1.305e+03  1.835e+02   7.111 1.26e-12 ***
Customer_Age                     1.382e+01  8.214e+00   1.683 0.092498 .  
GenderM                          4.280e+02  2.332e+02   1.835 0.066544 .  
Dependent_count                  1.586e+02  5.082e+01   3.120 0.001814 ** 
Marital_StatusMarried           -9.437e+02  2.548e+02  -3.704 0.000214 ***
Marital_StatusSingle            -3.516e+02  2.581e+02  -1.362 0.173094    
Marital_StatusUnknown           -3.910e+02  3.355e+02  -1.166 0.243808    
Income_Category$40K - $60K      -1.173e+04  3.045e+02 -38.506  &lt; 2e-16 ***
Income_Category$60K - $80K      -8.009e+03  2.819e+02 -28.414  &lt; 2e-16 ***
Income_Category$80K - $120K     -3.045e+03  2.768e+02 -10.999  &lt; 2e-16 ***
Income_CategoryLess than $40K   -1.247e+04  3.350e+02 -37.226  &lt; 2e-16 ***
Card_CategoryGold                1.624e+04  6.053e+02  26.833  &lt; 2e-16 ***
Card_CategoryPlatinum            1.626e+04  1.632e+03   9.965  &lt; 2e-16 ***
Card_CategorySilver              1.343e+04  2.874e+02  46.747  &lt; 2e-16 ***
Total_Trans_Amt                  1.429e-01  1.941e-02   7.359 2.05e-13 ***
Avg_Utilization_Ratio           -7.881e+03  2.588e+02 -30.456  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5629 on 7624 degrees of freedom
Multiple R-squared:  0.6233,    Adjusted R-squared:  0.6225 
F-statistic: 788.4 on 16 and 7624 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The model increases its explainability a bit but not enough.</p>
</section>
<section id="correlation-with-numeric-values" class="level4">
<h4 class="anchored" data-anchor-id="correlation-with-numeric-values">Correlation with numeric values</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>significantVariables_numeric <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">c</span>(<span class="dv">11</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">12</span>, <span class="dv">14</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">rcorr</span>(<span class="fu">as.matrix</span>(significantVariables_numeric)) <span class="co"># rcorr() accepts matrices only</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="co"># display p-values (rounded to 3 decimals)</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(res<span class="sc">$</span>P, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      Credit_Limit Customer_Age Dependent_count Total_Trans_Amt
Credit_Limit                    NA        0.141           0.000           0.000
Customer_Age                 0.141           NA           0.000           0.000
Dependent_count              0.000        0.000              NA           0.091
Total_Trans_Amt              0.000        0.000           0.091              NA
Avg_Utilization_Ratio        0.000        0.703           0.001           0.000
                      Avg_Utilization_Ratio
Credit_Limit                          0.000
Customer_Age                          0.703
Dependent_count                       0.001
Total_Trans_Amt                       0.000
Avg_Utilization_Ratio                    NA</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(significantVariables_numeric[, <span class="fu">c</span>(<span class="st">"Customer_Age"</span>, <span class="st">"Dependent_count"</span>, <span class="st">"Total_Trans_Amt"</span>, <span class="st">"Avg_Utilization_Ratio"</span> )])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CreditLimit_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(significantVariables_numeric<span class="sc">$</span>Avg_Utilization_Ratio,significantVariables_numeric<span class="sc">$</span>Customer_Age)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  x and y
t = 0.38137, df = 7639, p-value = 0.7029
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.01806100  0.02678329
sample estimates:
        cor 
0.004363341 </code></pre>
</div>
</div>
<p>The <em>p</em>-value of the correlation test between these 2 variables is 0.7029 . At the 5% significance level, we do not reject the null hypothesis of no correlation. We therefore conclude that we do not reject the hypothesis that there is no linear relationship between the 2 variables.</p>
<p>This test proves that even if the correlation coefficient is different from 0 (the correlation is 0.004363341 in the sample), it is actually not significantly different from 0 in the population.</p>
</section>
<section id="variance-inflation-factor-vif" class="level4">
<h4 class="anchored" data-anchor-id="variance-inflation-factor-vif">Variance Inflation Factor (VIF)</h4>
<p>A measure of the impact of collinearity on the precision of estimation of a coefficient.</p>
<p><span class="math display">\[
\text{Variance Inflation Factor} = 1/ (1 –R^2) = 1 / \text{Tolerance}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>vif_values <span class="ot">&lt;-</span>  <span class="fu">vif</span>(lmcreditlimitbetter)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>vif_values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          GVIF Df GVIF^(1/(2*Df))
Attrition_Flag        1.083123  1        1.040732
Customer_Age          1.030411  1        1.015091
Gender                3.270222  1        1.808376
Dependent_count       1.036594  1        1.018132
Marital_Status        1.017615  3        1.002915
Income_Category       3.388456  4        1.164797
Card_Category         1.095753  3        1.015357
Total_Trans_Amt       1.085860  1        1.042046
Avg_Utilization_Ratio 1.248869  1        1.117528</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(vif_values, <span class="at">main =</span> <span class="st">"VIF Values"</span>, <span class="at">horiz =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"steelblue"</span>) </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">5</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">lty =</span> <span class="dv">2</span>)    <span class="co">#add vertical line at 5 as after 5 there is severe correlation</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CreditLimit_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>GVIF is calculated instead of VIF when one of the degrees of freedoms is different from 1.</p>
<p>As table suggests, Income_Category and Gender might be problematic.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmcreditlimitbetter)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6232805</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>lmcreditlimit3 <span class="ot">&lt;-</span> <span class="fu">update</span>(lmcreditlimitbetter, . <span class="sc">~</span> . <span class="sc">-</span> Gender)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmcreditlimit3)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6231141</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>lmcreditlimit4 <span class="ot">&lt;-</span> <span class="fu">update</span>(lmcreditlimitbetter, . <span class="sc">~</span> . <span class="sc">-</span> Income_Category)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmcreditlimit4)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5181452</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>lmcreditlimit5 <span class="ot">&lt;-</span> <span class="fu">update</span>(lmcreditlimitbetter, . <span class="sc">~</span> . <span class="sc">-</span> Gender<span class="sc">-</span>Income_Category<span class="sc">-</span>Marital_Status)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmcreditlimit5)<span class="sc">$</span>r.squared</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4103301</code></pre>
</div>
</div>
<p>In this case, it seems that the first apparent problem is with the&nbsp;<code>Gender</code>&nbsp;variable in the model. We might try to correct this by excluding the this predictor; by doing so, we see that the&nbsp;<span class="math inline">\(R^2\)</span>&nbsp;value of the model will not decrease by considerable value. It implies that its contribution is already being provided by other predictor so does not need to retain in the model.</p>
<p>Not as much as <code>Gender</code>, but <code>Income_Category</code> stays at the same position. In fact, both of them can be eliminated.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmcreditlimit5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Credit_Limit ~ Attrition_Flag + Customer_Age + Dependent_count + 
    Card_Category + Total_Trans_Amt + Avg_Utilization_Ratio, 
    data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-20651.8  -3809.0   -988.6   2181.2  26311.6 

Coefficients:
                                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                      6.418e+03  5.661e+02  11.338  &lt; 2e-16 ***
Attrition_FlagExisting Customer  2.139e+03  2.282e+02   9.372  &lt; 2e-16 ***
Customer_Age                     3.737e+01  1.022e+01   3.658 0.000256 ***
Dependent_count                  3.588e+02  6.303e+01   5.693 1.29e-08 ***
Card_CategoryGold                1.709e+04  7.561e+02  22.605  &lt; 2e-16 ***
Card_CategoryPlatinum            1.784e+04  2.039e+03   8.751  &lt; 2e-16 ***
Card_CategorySilver              1.357e+04  3.591e+02  37.800  &lt; 2e-16 ***
Total_Trans_Amt                  1.217e-01  2.422e-02   5.025 5.15e-07 ***
Avg_Utilization_Ratio           -1.343e+04  3.031e+02 -44.307  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7039 on 7632 degrees of freedom
Multiple R-squared:  0.4103,    Adjusted R-squared:  0.4097 
F-statistic: 663.9 on 8 and 7632 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>In this model all predictors contributes significantly and the data is explained by %40.97 and the p-value is still quite low.</p>
</section>
<section id="tolerance-and-vif" class="level4">
<h4 class="anchored" data-anchor-id="tolerance-and-vif">Tolerance and VIF</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ols_vif_tol</span>(lmcreditlimit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                         Variables Tolerance      VIF
1  Attrition_FlagExisting Customer 0.8587025 1.164548
2                     Customer_Age 0.3726404 2.683552
3                          GenderM 0.3054520 3.273836
4                  Dependent_count 0.9638246 1.037533
5         Education_LevelDoctorate 0.7382776 1.354504
6          Education_LevelGraduate 0.3850197 2.597270
7       Education_LevelHigh School 0.4377633 2.284339
8     Education_LevelPost-Graduate 0.6998522 1.428873
9        Education_LevelUneducated 0.4932644 2.027310
10           Marital_StatusMarried 0.2563077 3.901560
11            Marital_StatusSingle 0.2625845 3.808298
12           Marital_StatusUnknown 0.5422366 1.844214
13      Income_Category$40K - $60K 0.2801593 3.569398
14      Income_Category$60K - $80K 0.3958596 2.526148
15     Income_Category$80K - $120K 0.3790857 2.637926
16   Income_CategoryLess than $40K 0.1547407 6.462425
17               Card_CategoryGold 0.9721490 1.028649
18           Card_CategoryPlatinum 0.9924194 1.007638
19             Card_CategorySilver 0.9386743 1.065332
20                  Months_on_book 0.3769406 2.652938
21                 Total_Trans_Amt 0.9188121 1.088362
22             Total_Ct_Chng_Q4_Q1 0.9153323 1.092499
23           Avg_Utilization_Ratio 0.7995378 1.250723</code></pre>
</div>
</div>
<ul>
<li><p>Tolerance of &lt;0.1 might indicate multicollinearity.</p></li>
<li><p>VIF exceeding 5 requires further investigation, whereas the VIF higher than 10 directly indicates multicollinearity.&nbsp;</p></li>
<li><p>Ideally, VIF should be lower than 3.</p>
<p>As follows these steps, only <code>Income_Category - Less than $40K</code> needs to be further investigated.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>data2 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Income_Category <span class="sc">!=</span> <span class="st">"Less than $40K"</span>)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>data2 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Marital_Status <span class="sc">!=</span> <span class="st">"Married"</span>)                          </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,446 × 14
   CLIENTNUM Attrition_Flag  Customer_Age Gender Dependent_count Education_Level
   &lt;chr&gt;     &lt;chr&gt;                  &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt; &lt;chr&gt;          
 1 818906208 Existing Custo…           32 M                    0 High School    
 2 710930508 Existing Custo…           37 M                    3 Uneducated     
 3 719661558 Existing Custo…           48 M                    2 Graduate       
 4 708790833 Existing Custo…           42 M                    5 Uneducated     
 5 710599683 Existing Custo…           56 M                    1 College        
 6 816082233 Existing Custo…           35 M                    3 Graduate       
 7 709967358 Existing Custo…           48 M                    4 Post-Graduate  
 8 806165208 Existing Custo…           47 M                    1 Doctorate      
 9 720466383 Existing Custo…           59 M                    1 High School    
10 715190283 Existing Custo…           57 F                    1 Graduate       
# ℹ 2,436 more rows
# ℹ 8 more variables: Marital_Status &lt;chr&gt;, Income_Category &lt;chr&gt;,
#   Card_Category &lt;chr&gt;, Months_on_book &lt;dbl&gt;, Credit_Limit &lt;dbl&gt;,
#   Total_Trans_Amt &lt;dbl&gt;, Total_Ct_Chng_Q4_Q1 &lt;dbl&gt;,
#   Avg_Utilization_Ratio &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>lmcreditlimit2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Credit_Limit <span class="sc">~</span> . <span class="sc">-</span>CLIENTNUM<span class="sc">-</span>Months_on_book <span class="sc">-</span> Total_Ct_Chng_Q4_Q1 <span class="sc">-</span>Customer_Age <span class="sc">-</span>Dependent_count <span class="sc">-</span>Education_Level , data2)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmcreditlimit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Credit_Limit ~ . - CLIENTNUM - Months_on_book - 
    Total_Ct_Chng_Q4_Q1 - Customer_Age - Dependent_count - Education_Level, 
    data = data2)

Residuals:
     Min       1Q   Median       3Q      Max 
-23781.6  -4575.5   -163.9   3458.8  20550.9 

Coefficients:
                                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                      1.819e+04  6.038e+02  30.132  &lt; 2e-16 ***
Attrition_FlagExisting Customer  1.954e+03  2.812e+02   6.948 4.23e-12 ***
GenderM                         -1.857e+02  3.450e+02  -0.538   0.5903    
Marital_StatusMarried           -9.787e+02  3.843e+02  -2.547   0.0109 *  
Marital_StatusSingle            -1.933e+02  3.902e+02  -0.496   0.6202    
Marital_StatusUnknown           -4.248e+02  5.043e+02  -0.842   0.3996    
Income_Category$40K - $60K      -1.082e+04  3.784e+02 -28.598  &lt; 2e-16 ***
Income_Category$60K - $80K      -7.568e+03  3.326e+02 -22.757  &lt; 2e-16 ***
Income_Category$80K - $120K     -2.860e+03  3.263e+02  -8.764  &lt; 2e-16 ***
Card_CategoryGold                1.741e+04  8.175e+02  21.300  &lt; 2e-16 ***
Card_CategoryPlatinum            1.750e+04  2.222e+03   7.872 4.32e-15 ***
Card_CategorySilver              1.494e+04  3.970e+02  37.641  &lt; 2e-16 ***
Total_Trans_Amt                  1.522e-01  2.748e-02   5.537 3.24e-08 ***
Avg_Utilization_Ratio           -1.449e+04  4.351e+02 -33.309  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6636 on 4622 degrees of freedom
Multiple R-squared:  0.597, Adjusted R-squared:  0.5958 
F-statistic: 526.6 on 13 and 4622 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>As it can be seen Adjusted R-squared is 0.5959 in <strong>lmcreditlimit2</strong> which is higher than <strong>lmcreditlimit5</strong> at previous part. So that, <code>Income_Category - Less than $40K</code> may cause the collinearity and just removing it by holding other income types will explain better .</p>
</section>
<section id="aic-and-bic" class="level4">
<h4 class="anchored" data-anchor-id="aic-and-bic">AIC and BIC</h4>
<p>AIC (Akaike, 1974) and the Bayesian information criterion – BIC (Schwarz, 1978) are measures of the goodness of fit of the linear regression model and can also be used for model selection (depend on the maximised value of the likelihood function L for the estimated model).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(lmcreditlimit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 94767.93</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(lmcreditlimit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 94864.55</code></pre>
</div>
</div>
</section>
<section id="model-accuracy" class="level4">
<h4 class="anchored" data-anchor-id="model-accuracy">Model Accuracy</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="co"># dividing the complete dataset into 2 parts having ratio of 70% and 30%</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>spl <span class="ot">=</span> <span class="fu">sample.split</span>(data2<span class="sc">$</span>Credit_Limit, <span class="at">SplitRatio =</span> <span class="fl">0.7</span>)</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>train <span class="ot">=</span> <span class="fu">subset</span>(data2, spl <span class="sc">==</span> <span class="cn">TRUE</span>, <span class="at">select=</span><span class="sc">-</span>CLIENTNUM)</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>test <span class="ot">=</span> <span class="fu">subset</span>(data2, spl <span class="sc">==</span> <span class="cn">FALSE</span>, <span class="at">select=</span><span class="sc">-</span>CLIENTNUM)</span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">dim</span>(train))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3245   13</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">dim</span>(test))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1391   13</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>model_lm <span class="ot">=</span> <span class="fu">lm</span>(Credit_Limit <span class="sc">~</span> .,<span class="at">data =</span> train, <span class="at">maxit =</span> <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>predictTest <span class="ot">=</span> <span class="fu">as.factor</span>(<span class="fu">predict</span>(model_lm, test))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>actuals_preds <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">cbind</span>(<span class="at">actuals=</span>test<span class="sc">$</span>Credit_Limit, <span class="at">predicteds=</span>predictTest)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>correlation_accuracy <span class="ot">&lt;-</span> <span class="fu">cor</span>(actuals_preds)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>correlation_accuracy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             actuals predicteds
actuals    1.0000000  0.7481605
predicteds 0.7481605  1.0000000</code></pre>
</div>
</div>
<p>A higher <strong>correlation accuracy</strong> implies that the actuals and predicted values have similar directional movement, i.e.&nbsp;when the actuals values increase the predicted values also increase.</p>
</section>
<section id="decision-tree" class="level4">
<h4 class="anchored" data-anchor-id="decision-tree">Decision Tree</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>tree.creditlimit <span class="ot">&lt;-</span> <span class="fu">tree</span>(Credit_Limit <span class="sc">~</span> <span class="fu">unlist</span>(Attrition_Flag)<span class="sc">+</span><span class="fu">unlist</span>(Marital_Status)<span class="sc">+</span><span class="fu">unlist</span>(Card_Category)<span class="sc">+</span><span class="fu">unlist</span>(Income_Category)<span class="sc">+</span><span class="fu">unlist</span>(Avg_Utilization_Ratio)<span class="sc">+</span><span class="fu">unlist</span>(Total_Trans_Amt) , <span class="at">data =</span> train)</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tree.creditlimit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Regression tree:
tree(formula = Credit_Limit ~ unlist(Attrition_Flag) + unlist(Marital_Status) + 
    unlist(Card_Category) + unlist(Income_Category) + unlist(Avg_Utilization_Ratio) + 
    unlist(Total_Trans_Amt), data = train)
Variables actually used in tree construction:
[1] "unlist(Avg_Utilization_Ratio)"
Number of terminal nodes:  6 
Residual mean deviance:  41930000 = 1.358e+11 / 3239 
Distribution of residuals:
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
-25700.0  -3100.0   -409.3      0.0   2626.0  23250.0 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(tree.creditlimit)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(tree.creditlimit, <span class="at">pretty=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CreditLimit_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid" width="1440"></p>
</div>
</div>
<p><strong>Single-predictor tree:</strong> This indicates that the selected predictor which is <code>Avg_Utilization_Ratio</code> in this case is much more significant than the others. This may imply that there is no need to other predictors somehow. On the other hand, this may occur when the dataset is not complex, a single variable can help readers to understand the data. Last but not least, a poorly constructed dataset can also cause this situation.</p>
</section>
<section id="random-forest" class="level4">
<h4 class="anchored" data-anchor-id="random-forest">Random Forest</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>tree.creditlimit2 <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(Credit_Limit <span class="sc">~</span> . , <span class="at">data =</span> train, <span class="at">importance=</span> <span class="cn">TRUE</span>)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>tree.creditlimit2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
 randomForest(formula = Credit_Limit ~ ., data = train, importance = TRUE) 
               Type of random forest: regression
                     Number of trees: 500
No. of variables tried at each split: 4

          Mean of squared residuals: 24247013
                    % Var explained: 77.34</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">importance</span>(tree.creditlimit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          %IncMSE IncNodePurity
Attrition_Flag         16.4660486    3737878491
Customer_Age            7.0120032   11050884239
Gender                 27.4620322   13878091340
Dependent_count         6.4724717    6203017290
Education_Level        -2.2092930    5505990612
Marital_Status          0.2707152    4541357773
Income_Category        56.2384376   40036877963
Card_Category          66.8953109   60519776225
Months_on_book          8.6680421   10264619358
Total_Trans_Amt        19.1161949   21215791161
Total_Ct_Chng_Q4_Q1     8.8957624   14616790392
Avg_Utilization_Ratio 118.7226759  145342755227</code></pre>
</div>
</div>
<div class="cell" data-fig.asp="0.614">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">varImpPlot</span>(tree.creditlimit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CreditLimit_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>As we estimated, <code>Avg_Utilization_Ratio</code> is the pioneer for explaining the all dataset. <code>Card_Category</code>and <code>Income_Category</code> are also important for the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>lmlast <span class="ot">&lt;-</span> <span class="fu">lm</span>(Credit_Limit <span class="sc">~</span>Avg_Utilization_Ratio <span class="sc">+</span> Card_Category<span class="sc">+</span> Income_Category, data)</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmlast)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Credit_Limit ~ Avg_Utilization_Ratio + Card_Category + 
    Income_Category, data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-20924.8  -3714.2    314.7   2486.9  19169.8 

Coefficients:
                              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    18949.1      235.8   80.35   &lt;2e-16 ***
Avg_Utilization_Ratio          -7677.0      254.5  -30.16   &lt;2e-16 ***
Card_CategoryGold              16913.7      606.6   27.88   &lt;2e-16 ***
Card_CategoryPlatinum          16906.7     1645.8   10.27   &lt;2e-16 ***
Card_CategorySilver            13881.0      287.4   48.30   &lt;2e-16 ***
Income_Category$40K - $60K    -11993.1      277.4  -43.23   &lt;2e-16 ***
Income_Category$60K - $80K     -7988.9      284.3  -28.10   &lt;2e-16 ***
Income_Category$80K - $120K    -3042.6      279.4  -10.89   &lt;2e-16 ***
Income_CategoryLess than $40K -12943.0      260.7  -49.65   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5689 on 7632 degrees of freedom
Multiple R-squared:  0.6149,    Adjusted R-squared:  0.6144 
F-statistic:  1523 on 8 and 7632 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Indeed, Adjusted R^2 increased with these 3 variables and all predictors have very low p-value.</p>
<div class="cell" data-fig.asp="0.614">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lmlast)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="CreditLimit_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>